"use strict";

export default {
  activeMonthIndex: 0,
  checkIn: this.startingDateValue,
  checkIncheckOutHalfDay: {},
  checkInPeriod: {},
  checkOut: this.endingDateValue,
  hoveringPeriod: {},
  customTooltip: '',
  customTooltipHalfday: '',
  datepickerDayKey: 0,
  datepickerMonthKey: 0,
  datepickerWeekKey: 0,
  dynamicNightCounts: null,
  hash: Date.now(),
  hoveringDate: null,
  isTouchMove: false,
  months: [],
  nextDisabledDate: null,
  nextPeriodDisableDates: [],
  open: false,
  screenSize: null,
  showCustomTooltip: false,
  sortedDisabledDates: null,
  xDown: null,
  xUp: null,
  yDown: null,
  yUp: null,
};